In [ ]:
import pandas as pd

from inference import load_data

# sentiment = 0 :positive, 1:negative, 2:neutral
data = load_data(
    "restaurant",
    seed=42,
)
for idx, x in zip(data.index, [1, 2, 3, 4, 5]):
    print(idx, x)
print(type(idx))
data.head()

0 1
1 2
2 3
3 4
4 5
<class 'int'>

,sentence,object,sentiment,is implicit
0,the bread is top notch as well.,bread,0,0
1,i have to say they have one of the fastest del...,delivery times,0,0
2,food is always fresh and hot- ready to eat!,Food,0,0
3,did i mention that the coffee is outstanding?,coffee,0,0
4,"certainly not the best sushi in new york, howe...",place,0,0

In [8]:
idx = 10
x = data[data["sentiment"] == 2]
print(x.iloc[idx])
print(x.iloc[idx]["sentence"])

sentence       even when the chef is not in the house, the fo...
object                                                      chef
sentiment                                                      2
is implicit                                                    1
Name: 176, dtype: object
even when the chef is not in the house, the food and service are right on target.

In [13]:
import pandas as pd
import numpy as np

test = pd.read_parquet("./data/output/laptop_test.parquet")
print(f"{test.shape = }")
test.head()

test.shape = (81664, 3)

   index                                             output  output_tokens
0      0  The sentence describes boot time as "super fas...             41
1      0  The sentence describes boot time as "super fas...             42
2      0  The sentence describes boot time as "super fas...             42
3      0  The sentence states that boot time is "super f...             42
4      0  The sentence states that "boot time is super f...             47

In [10]:
out_toks = np.array(test["output_tokens"])
out_toks.mean(), out_toks.std(), out_toks.max(), out_toks.min()

(np.float64(46.03828125),
 np.float64(18.48631512892438),
 np.int64(167),
 np.int64(21))

In [11]:
test["output"][10]

'The sentiment towards the weight of the object is described as "acceptable," which implies it is satisfactory or meets expectations without being excessive or unfavorable. This indicates a neutral to slightly positive tone, but since "acceptable" does not convey strong approval, it leans more toward neutrality.\n\nneutral'

In [12]:
with open("./data/preprocessed/restaurants_base_google-flan-t5-base.pkl", "rb") as f:
    data = pickle.load(f)
data = pd.DataFrame(data)
data.columns = ["sentence", "object", "sentiment", "is implicit"]
print(f"{data.shape = }")
print(f"{data['sentiment'].value_counts(normalize=True) = }")
print(f"{data['is implicit'].value_counts(normalize=True) = }")
data

NameError: name 'pickle' is not defined

In [ ]:
with open(
    "./data/laptops/Laptops_Test_Gold_Implicit_Labeled_preprocess_finetune.pkl", "rb"
) as f:
    data = pickle.load(f)
data = pd.DataFrame(data)
print(f"Laptops_Test_Gold_Implicit_Labeled_preprocess_finetune:{data.shape = }")
print(f"{data[2].value_counts(normalize=True)}")
print(f"{data[3].value_counts(normalize=True)}")
print()

with open(
    "./data/laptops/Laptops_Train_v2_Implicit_Labeled_preprocess_finetune.pkl", "rb"
) as f:
    data = pickle.load(f)
data = pd.DataFrame(data)
print(f"Laptops_Train_v2_Implicit_Labeled_preprocess_finetune:{data.shape = }")
print(f"{data[2].value_counts(normalize=True)}")
print(f"{data[3].value_counts(normalize=True)}")
print()

with open(
    "./data/restaurants/Restaurants_Test_Gold_Implicit_Labeled_preprocess_finetune.pkl",
    "rb",
) as f:
    data = pickle.load(f)
data = pd.DataFrame(data)
print(f"Restaurants_Test_Gold_Implicit_Labeled_preprocess_finetune:{data.shape = }")
print(f"{data[2].value_counts(normalize=True)}")
print(f"{data[3].value_counts(normalize=True)}")
print()

with open(
    "./data/restaurants/Restaurants_Train_v2_Implicit_Labeled_preprocess_finetune.pkl",
    "rb",
) as f:
    data = pickle.load(f)
data = pd.DataFrame(data)
print(f"Restaurants_Train_v2_Implicit_Labeled_preprocess_finetune:{data.shape = }")
print(f"{data[2].value_counts(normalize=True)}")
print(f"{data[3].value_counts(normalize=True)}")
print()

Laptops_Test_Gold_Implicit_Labeled_preprocess_finetune:data.shape = (638, 4)
2
0    0.534483
2    0.264890
1    0.200627
Name: proportion, dtype: float64
3
0    0.725705
1    0.274295
Name: proportion, dtype: float64

Laptops_Train_v2_Implicit_Labeled_preprocess_finetune:data.shape = (2313, 4)
2
0    0.426719
1    0.374406
2    0.198876
Name: proportion, dtype: float64
3
0    0.690445
1    0.309555
Name: proportion, dtype: float64

Restaurants_Test_Gold_Implicit_Labeled_preprocess_finetune:data.shape = (1120, 4)
2
0    0.650
2    0.175
1    0.175
Name: proportion, dtype: float64
3
0    0.761607
1    0.238393
Name: proportion, dtype: float64

Restaurants_Train_v2_Implicit_Labeled_preprocess_finetune:data.shape = (3602, 4)
2
0    0.600777
1    0.223487
2    0.175736
Name: proportion, dtype: float64
3
0    0.714048
1    0.285952
Name: proportion, dtype: float64